# Bootloader installation module
---
efiBootLoader: "grub"

kernel: "/boot/vmlinuz"
img: "/boot/initramfs.cpio.gz"
fallback: "/boot/vmlinuz"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"

efiBootMgr: "efibootmgr"

installEpoxy: false
installGrub: true
