# Fstab module configuration for KratosOS
---
mountOptions:
    default: defaults,noatime
    ext4: defaults,noatime
    vfat: defaults,umask=0077

mountPoints:
    - mountPoint: /boot/efi
      options: umask=0077

usePartUUID: false
