# GRUB configuration file generation for KratosOS
---
overwrite: true
prefer_grub_d: false
keep_old_entries: false

defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: 0
    GRUB_DISTRIBUTOR: "KratosOS"
    GRUB_CMDLINE_LINUX_DEFAULT: "quiet loglevel=3 init=/sbin/init"
    GRUB_CMDLINE_LINUX: ""
    GRUB_TERMINAL_INPUT: "console"
    GRUB_TERMINAL_OUTPUT: "console gfxterm"
    GRUB_GFXMODE: "auto"
