# Partition module configuration
---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 256M

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawPartitionTable: true

alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice: none

defaultFileSystemType: "ext4"

availableFileSystemTypes:
    - ext4
    - ext3
    - btrfs
    - xfs
