# Unpackfs module configuration for KratosOS
---
unpack:
    - source: "/"
      sourcefs: "rootfs"
      destination: ""
      exclude:
          - "/proc/*"
          - "/sys/*"
          - "/dev/*"
          - "/run/*"
          - "/tmp/*"
          - "/mnt/*"
          - "/media/*"
          - "/lost+found"
          - "/boot/efi/*"
          - "/etc/rc.d/99-live"
          - "/home/kratos-live"
          - "/root/.xinitrc"
