# Users module configuration
---
defaultGroups:
    - wheel
    - audio
    - video
    - input
    - disk
    - users

autologinGroup: wheel
sudoersGroup: wheel
setRootPassword: true
doAutologin: false
passwordRequirements:
    nonempty: true
