Section "OutputClass"
    Identifier "modesetting"
    MatchDriver "i915|amdgpu|radeon|nouveau|vmwgfx|bochs-drm|virtio-gpu|vboxvideo|qxl|simpledrm|ast|mgag200"
    Driver "modesetting"
    Option "PrimaryGPU" "true"
    Option "SWCursor" "on"
EndSection
